drivers: input: touchscreen: ili9881h: Fix missing type specifier
* Causing error while building using clang 15

../drivers/input/touchscreen/ili9881h/ilitek_mp.c:309:8: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
extern mp_test_result;
~~~~~~ ^
int

Signed-off-by: dodyirawan85 <40514988+dodyirawan85@users.noreply.github.com>